//$file${.::AO_ESP32C_Signals.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: AO_ESP32C.qm
// File:  ${.::AO_ESP32C_Signals.h}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::AO_ESP32C_Signals.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef __AOESP32CSIGNALS_HP
#define __AOESP32CSIGNALS_HP

#define FOREACH_ESP32C_SIGNALS(MACRO)             \
                         MACRO(      ESP32C_OK_SIG                )\
                         MACRO(      ESP32C_ERR_SIG               )\
                         MACRO(      ESP32C_START_SIG             )\
                         MACRO(      ESP32C_TCP_CONNECT_SIG       )\
                         MACRO(      ESP32C_UDP_CONNECT_SIG       )\
                         MACRO(      ESP32C_CLOSE_SOCKET_SIG      )\
                         MACRO(      ESP32C_READ_DATA_SIG         )\
                         MACRO(      ESP32C_SEND_DATA_SIG         )\
                         MACRO(      ESP32C_OPEN_SERVER_SIG       )\
                         MACRO(      ESP32C_HOTSPOT_CONFIG_SIG    )\
                         MACRO(      ESP32C_DATA_RECEIVE_CHECK_SIG  )\
                         MACRO(      ESP32C_UNSOLICITED_STA_SIG     )\
                         MACRO(      ESP32C_UNSOLICITED_END_SIG     )\
                         MACRO(      ESP32C_UNSOLICITED_TIMEOUT_SIG )\
                         MACRO(      ESP32C_WEBSOCKET_OPEN_SIG      )\
                         MACRO(      ESP32C_WEBSOCKET_CLOSE_SIG     )\
                         MACRO(      ESP32C_WEBSOCKET_SEND_DATA_SIG )\
                         MACRO(      ESP32C_CONNECTION_CHECK_SIG    )\
                         MACRO(      ESP32C_CONNECT_WIFI_SIG        )

#define __ESP32C_SIGNAL_DEF(SIG)      SIG
#define __ESP32C_SIGNAL_ENUM(SIG)     SIG,
#define ESP32C_SIGNALS_DEF     FOREACH_ESP32C_SIGNALS(__ESP32C_SIGNAL_DEF)
#define ESP32C_SIGNALS_ENUM    FOREACH_ESP32C_SIGNALS(__ESP32C_SIGNAL_ENUM)
#endif
