//$file${.::AO_ESP32C.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: AO_ESP32C.qm
// File:  ${.::AO_ESP32C.hpp}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::AO_ESP32C.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef AO_ESP32C_H
#define AO_ESP32C_H

#include "ESP32C.hpp"
#include "qpcpp.hpp" // QP/C++ framework API
#include "Signals.hpp"
#include "BSP_QP.hpp"
#include "Debug_Print.hpp"
#include "string.h"

#define PWD_MAX_LEN 64
#define SSID_MAX_LEN 64
#define ESP32C_RESET_INTERVAL_MS 1500
#define ESP32C_WIFI_CONN_INTERVAL_MS 25000
#define ESP32C_TIMEOUT_MS 5000
#define ESP32C_UNSOLICITED_TIMEOUT_MS 25
#define ESP32C_INCOMING_DATA_CHECK_PERIOD_MS 100
#define ESP32C_TCP_INTERVAL_MS 15000
#define ESP32C_RETRY_MAX 2
#define ADDRESS_LEN_MAX 100
#define ESP32C_URI_MAX_LEN 256
#define ESP32C_TX_BUFFER_LEN 2048
#define ESP32C3_WS_HEADER_MAX_LEN 128
#define ESP32C_WS_INTERVAL_MS  (ESP32C_TCP_INTERVAL_MS)
#define ESP32C_TIMEOUT_COUNT_MAX 10
#define ESP32C_AO_MAX_DEFERRED_EVENTS 32
#define ESP32C_AO_CONNECTION_CHECK_PERIOD_MS (10000)

#define ESP32C_SOCKET_STATUS_CLOSE       0 ///< socket close
#define ESP32C_SOCKET_STATUS_OPEN        1 ///< tcp socket open
#define ESP32C_SOCKET_STATUS_WS_OPEN     2 ///< websocket open
#define ESP32C_SOCKET_STATUS_SERVER_OPEN 3 ///< socket opened when esp32c3 acts as server
//$declare${AOs::CloseSocketEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AO {

//${AOs::CloseSocketEvt} .....................................................
///@brief event to relay the closure of a socket
class CloseSocketEvt : public QP::QEvt {
public:

    ///@brief socket id to be closed
    DRV::ESP32C3::LinkId socket_id= DRV::ESP32C3::LinkId0;
}; // class CloseSocketEvt

} // namespace AO
//$enddecl${AOs::CloseSocketEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::AO_ESP32C_StartEvent} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AO {

//${AOs::AO_ESP32C_StartEvent} ...............................................
class AO_ESP32C_StartEvent : public QP::QEvt {
public:
    DRV::ESP32C3::WiFiMode mode;
}; // class AO_ESP32C_StartEvent

} // namespace AO
//$enddecl${AOs::AO_ESP32C_StartEvent} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::SendDataEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AO {

//${AOs::SendDataEvt} ........................................................
///@brief event to send data
class SendDataEvt : public QP::QEvt {
public:
    uint8_t data[ESP32C_TX_BUFFER_LEN]={0};
    uint16_t length= 0;
    DRV::ESP32C3::LinkId socket_id;
    DRV::ESP32C3::WebSockedtOpCode_t opcode;
}; // class SendDataEvt

} // namespace AO
//$enddecl${AOs::SendDataEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::OpenTcpSocketEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AO {

//${AOs::OpenTcpSocketEvt} ...................................................
class OpenTcpSocketEvt : public QP::QEvt {
public:
    uint8_t address[ADDRESS_LEN_MAX]= {0};
    uint16_t port= 0;
}; // class OpenTcpSocketEvt

} // namespace AO
//$enddecl${AOs::OpenTcpSocketEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::OpenWsSocketEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AO {

//${AOs::OpenWsSocketEvt} ....................................................
class OpenWsSocketEvt : public QP::QEvt {
public:
    uint8_t ws_uri[ESP32C_URI_MAX_LEN]= {0};
    uint16_t ws_uri_len= 0;
    uint32_t ws_ping_timeout_s= 0;
    uint32_t ws_ping_interval_s= 0;
    uint8_t ws_header[ESP32C3_WS_HEADER_MAX_LEN]= {0};
    uint16_t ws_header_len= 0;
    uint8_t ws_auth[ESP32C_URI_MAX_LEN]= {0};
    uint16_t ws_auth_len= 0;
    uint8_t ws_sub_protocol[ESP32C_URI_MAX_LEN]= {0};
    uint16_t ws_sub_protocol_len= 0;
}; // class OpenWsSocketEvt

} // namespace AO
//$enddecl${AOs::OpenWsSocketEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::ConnectApEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AO {

//${AOs::ConnectApEvt} .......................................................
class ConnectApEvt : public QP::QEvt {
public:
    uint8_t ssid[SSID_MAX_LEN]= {0};
    uint16_t pwd[PWD_MAX_LEN]= {0};
}; // class ConnectApEvt

} // namespace AO
//$enddecl${AOs::ConnectApEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
namespace AO
{
    typedef struct
    {
        DRV::ESP32C3* esp;
        //QEQueue requestQueue; /* native QF queue for deferred request events */
        //QEvent const *requestQSto[3]; /* storage for the deferred queue buffer */
        QP::QEQueue* deferQueue;
    }ESP32C_Init_t;
};

// ask QM to declare the AO_ESP32C class ----------------------------------------

//$declare${AOs::AO_ESP32C} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AO {

//${AOs::AO_ESP32C} ..........................................................
class AO_ESP32C : public QP::QActive {
public:

    ///@brief internal timing event object
    QP::QTimeEvt m_timeEvt;

    ///@brief internal timing event object to periodically check incoming data
    QP::QTimeEvt m_incomingDataCheckTimeEvt;

    ///@brief internal timing event object to timeout unsolicited messages
    QP::QTimeEvt m_unsolicitedTimeEvt;

    ///@brief internal timer to periodically check connection status
    QP::QTimeEvt m_connectionCheckTimeEvt;

private:

    ///@biref init structure
    ESP32C_Init_t init;

    ///@brief esp32c operating mode (ap, station or both)
    DRV::ESP32C3::WiFiMode mode;
    uint8_t rx_buffer[ESP32C_TX_BUFFER_LEN]= {0};

    ///@brief  connection to a wifi network ssid buffer
    uint8_t ssid[SSID_MAX_LEN]= {0};

    ///@brief external wifi network password buffer
    uint8_t pwd[PWD_MAX_LEN]= {0};

    ///@brief generated hotspot ssid buffer
    uint8_t hotspot_ssid[SSID_MAX_LEN]= {0};

    ///@brief generated hotspot password buffer
    uint8_t hotspot_pwd[PWD_MAX_LEN]= {0};
    DRV::ESP32C3::WifiEncryption hotspot_encryption;
    uint8_t hotspot_max_conn;

    ///@brief hotspot generated to be hidden or not
    bool hotspot_hidden= false;

    ///@brief channel id for hotspot mode
    DRV::ESP32C3::WifiChannelIds hotspot_channel_id;

    ///@counter of errors
    uint8_t error_counter= 0;

    ///@brief remote url or ip buffer for socket connection
    uint8_t remote_address[ADDRESS_LEN_MAX]= {0};

    ///@brief remote port buffer for socket connection
    uint16_t remote_port= 0;
    DRV::ESP32C3::LinkId client_link_id= DRV::ESP32C3::LinkId1;

    ///@brief buffer to preserve parsing result of at command responses
    bool commandParseResult= false;

    ///@brief buffers data length info for data transmission
    uint32_t send_data_length= 0;

    ///@brief stores data to be sent via wifi
    uint8_t send_data_buffer[ESP32C_TX_BUFFER_LEN]= {0};

    ///@brief store the maximum data requested in bytes
    uint32_t receive_data_max_length = 0;

    ///@brief received data from wifi shall be copied into the memory location pointed by this pointer
    uint8_t* receive_data_buffer_ptr= nullptr;

    ///@brief user provided timeout value buffer in milliseconds
    uint32_t user_timeout_ms = 0;

    ///@brief counter used to memorize the amount of data stored in rx_buffer, so data received by the module via uart
    uint32_t rx_data_length= 0;

    ///@brief hold the link id to be closed
    DRV::ESP32C3::LinkId client_close_id= DRV::ESP32C3::LinkId0;

    ///@brief buffer for server port open to connection
    uint16_t server_port= 0;

    ///@brief array of socket statuses 0-> disconnected 1-> connected
    uint8_t socket_status[DRV::ESP32C3::LinkIdMax]= {ESP32C_SOCKET_STATUS_CLOSE};

    ///@brief flag that indicates the ongoing reception of an unsolicited message
    bool unsolicited_msg_flag= false;

    ///@brief maixmum number of simultaneous connections in server mode
    uint8_t  server_max_connections= 1;

    ///@brief ping interval parameter used to configure websockets in seconds
    uint32_t ws_ping_interval_s= 0;

    ///@brief ping timeout parameter used to configure websockets in seconds
    uint32_t ws_ping_timeout_s= 0;

    ///@brief  current header to be used in the next websocket connection
    uint8_t ws_header[ESP32C3_WS_HEADER_MAX_LEN]= {0};

    ///@brief current header length in bytes
    uint32_t ws_header_len = 0;

    ///@brief buffer for uri address
    uint8_t ws_uri[ESP32C_URI_MAX_LEN]= {0};

    ///@brief  opcode for next websocket operation
    DRV::ESP32C3::WebSockedtOpCode_t ws_opcode= DRV::ESP32C3::WebSockedtOpCode_t::ContinuationFrame;

public:

    ///@brief bytes composing the next uri to be used in a websocket open query
    uint32_t ws_uri_len= 0;

private:

    ///@brief counts timeout, no response from the module, if the number of consecutive timeouts exceeds  the limit, the ao  triggers a callback
    uint32_t timeout_counter= 0;

    ///@brief signals whther websocket at configuration is already established
    bool ws_cfg_done[ESP32C3_MAX_WS_SOCKET] = {0};

    ///@brief autorization parameter buffer for websocket
    uint8_t ws_auth[ESP32C_URI_MAX_LEN]= {0};

    ///@brief current auth parameter length
    uint32_t ws_auth_len = 0;

    ///@brief string defining websocket sub protocol
    uint8_t ws_sub_protocol[ESP32C_URI_MAX_LEN]= {0};

    ///@brief number of bytes of the sub prootocol parameter string
    uint16_t ws_sub_protocol_len = 0;

    ///@brief holds the port value used for udp listening
    uint8_t udp_local_port = 0;

    ///@brief stores the upd remote port for udp connections
    uint8_t udp_remote_port= 0;

    ///@brief indicates we are in  idle state
    bool idle_flag= false;

    ///@brief signals that the hotspot  mode is on
    bool hotspot_active= false;

public:
    AO_ESP32C(ESP32C_Init_t& _init);
    void Begin(
        DRV::ESP32C3::WiFiMode _mode,
        void* caller);

    /**@brief process hardware event callback data  obtained from uart communication
    *@parm event type
    *@param caller object
    *@param data payload
    */
    void ReceiveCompleteCallback(
        DRV::ESP32C3::Event  event,
        DRV::ESP32C3*  caller,
        uint8_t*  data);

    /**
    *@brief initiate connection procedure to a wifi via ssdi and password
    *@parm ssid string
    *@param password string
    *@param caller object
    */
    void WiFiConnect(
        const uint8_t* _ssid,
        const uint8_t* _pwd,
        void* caller);

    /**
    @brief  sends a requesto to the active object to configure  a esp32c hotspot
    @param ssid of the wifi
    @param password
    @param  connection channel used in the esp32c
    @param encryption type adopted by the esp32c
    @param maximum number of connections
    @param should the ssid hidden
    @param reference to caller object
    */
    void WiFiHotspotOpen(
        const uint8_t* _ssid,
        const uint8_t* _pwd,
        DRV::ESP32C3::WifiChannelIds _channel_id,
        DRV::ESP32C3::WifiEncryption _encryption,
        uint8_t _max_conn,
        bool _hidden,
        void* caller);

    /**
    *@brief  sends a requesto to open a tcp socket to         *       a remote address
    *@param  strting address or ip address
    *@param  number port
    *@param caller object for qp tracing
    */
    void TcpOpenSocket(
        const uint8_t* address,
        uint16_t port,
        void* caller);

    /**
    *@brief Trigger transmisison of data via socket *(previously opened)
    *@param data pointer
    *@param length in bytes
    *@param socket id to be used
    *@param caller object for qp tracing
    */
    bool SendData(
        const uint8_t* data,
        uint32_t length,
        DRV::ESP32C3::LinkId _socket_id,
        void* caller);

    /**
    *@brief Receive and read data from an open connection
    *@param pointer where data shall be stored
    *@param  max data length
    *@param timeout in ms
    *@param caller object for qp tracing
    */
    void ReadData(
        uint8_t* receive_buffer,
        uint32_t max_length,
        uint32_t timeout_ms,
        void* caller);

    /**
    *@brief closes a previously opened tcp socket
    *@param link id of the socket
    *@param caller object for qp tracing
    */
    void TcpCloseSocket(
        DRV::ESP32C3::LinkId socket_id,
        void* caller);

    /**
    *@brief issue request to open a  server on the desired port
    *@param port number
    *@param caller object for qp tracing
    *@param maximum number of simultaneous supported connections
    */
    void OpenServer(
        uint16_t port,
        void* caller,
        uint8_t _server_max_connections);

private:

    /**
    *@brief retrieve the first unoccupied socket id
    *@param return value pointer
    *@return 1-> found 0-> not found
    */
    uint8_t GetFreeSocketId(DRV::ESP32C3::LinkId* startOutput_socketId);

    /**
    *@brief retrieve the first unoccupied websocket socket id
    *@param return value pointer
    *@return 1-> found 0-> not found
    */
    uint8_t GetFreeWsSocketId(DRV::ESP32C3::LinkId* startOutput_socketId);

public:

    /**
    *@brief signals the state machine that an unsolicited message is being *received via uart
    *@param caller object for qp tracing
    */
    void NotifyUnsolicitedMsgBegin(void* caller);

    /**
    *@brief notify the state machine a complete unsolicited message has been received
    *@param caller object for qp tracing
    */
    void NotifyUnsolicitedMsgEnd(
        void* caller,
        DRV::ESP32C3::Event event,
        uint8_t* data);

    /**
    *@brief configures a websockets and opens it using a sequence of at commands, it posts the ESP32C_WEBSOCKET_OPEN_SIG
    *@param ping interval in seconds
    *@param ping timeout in seconds
    *@param pointer to websocket header, nullpointer i if no header required
    *@param websocket header length in bytes, input 0 if no header is required
    *@param uri address
    *@param length of uri
    *@param sub protocol  used by the websocket
    *@param length of the sub protocol string
    *@param auth string
    *@param auth string length
    *@param caller object
    *@return  true process initiates correctly, false wrong parameters event not posted
    */
    bool WebSocket_Open(
        uint32_t _ws_ping_interval_s,
        uint32_t _ws_ping_timeout_s,
        uint8_t* _ws_header,
        uint16_t _ws_header_len,
        uint8_t* _ws_uri,
        uint16_t _ws_uri_len,
        const uint8_t* _ws_sub_protocol,
        uint16_t _ws_sub_protocol_len,
        const uint8_t* _ws_auth,
        uint16_t _ws_auth_len,
        void* caller);

    /**
    *@brief Trigger transmisison of data via socket *(previously opened)
    *@param data pointer
    *@param length in bytes
    *@param socket id to be used
    *@param websocket opcode
    *@param caller object for qp tracing
    */
    bool WebSocket_SendData(
        const uint8_t* data,
        uint32_t length,
        DRV::ESP32C3::LinkId _socket_id,
        DRV::ESP32C3::WebSockedtOpCode_t _ws_opcode,
        void* caller);

    /**
    *@brief Trigger transmisison of data via socket *(previously opened)
    *@param data pointer
    *@param length in bytes
    *@param socket id to be used
    *@param websocket opcode
    *@param caller object for qp tracing
    *@param delay ticks for retry
    */
    bool WebSocket_SendData(
        const uint8_t* data,
        uint32_t length,
        DRV::ESP32C3::LinkId _socket_id,
        DRV::ESP32C3::WebSockedtOpCode_t _ws_opcode,
        void* caller,
        uint8_t delayTicks);

    /**
    *@brief closes a previously opened websocket
    *@param link id of the socket to be closed
    *@return success or failure
    */
    bool WebSocket_Close(
        DRV::ESP32C3::LinkId socket_id,
        void* caller);

    /**
    *@brief callback to signal that  the stream of an unsolicited message is continuing
    *@param calle robject
    */
    void NotifyUnsolicitedMsgCont(void* caller);

    /** @brief  open ad udp listening socket*/
    bool UdpOpen(
        uint8_t _local_port,
        uint8_t _remote_port,
        const uint8_t* address,
        void* caller);

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(InitState);
    Q_STATE_DECL(offState);
    Q_STATE_DECL(Idle_ConfiguredState);
    Q_STATE_DECL(HotspotConfigurationState);
    Q_STATE_DECL(Parse_CWSAP_Response);
    Q_STATE_DECL(SEND_AT_CWSAP);
    Q_STATE_DECL(WiFi_ConfigState);
    Q_STATE_DECL(Send_AT_CWJAP);
    Q_STATE_DECL(Parse_CWJAP_Response);
    Q_STATE_DECL(Idle_NetworkConnectedState);
    Q_STATE_DECL(Busy_NetworkConnectedState);
    Q_STATE_DECL(CloseTCPSocketState);
    Q_STATE_DECL(OpenTCPSocketState);
    Q_STATE_DECL(TransmitDataState);
    Q_STATE_DECL(InitiateSendDataState);
    Q_STATE_DECL(WaitingForDataState);
    Q_STATE_DECL(WebSocket_OpenState);
    Q_STATE_DECL(Send_AT_WSCFG);
    Q_STATE_DECL(Send_AT_WSHEAD);
    Q_STATE_DECL(Send_AT_WSOPEN);
    Q_STATE_DECL(Send_Header);
    Q_STATE_DECL(Websocket_SendState);
    Q_STATE_DECL(WebSocket_CloseState);
    Q_STATE_DECL(TransmitWebSocketDataState);
    Q_STATE_DECL(CreateServerState);
    Q_STATE_DECL(open_server);
    Q_STATE_DECL(UdpListenCommandState);
    Q_STATE_DECL(ConnectionCheckState);
    Q_STATE_DECL(Base_ConfigState);
    Q_STATE_DECL(SendAT);
    Q_STATE_DECL(SetMode);
    Q_STATE_DECL(ResetEnd);
    Q_STATE_DECL(SendCIPMUX);
    Q_STATE_DECL(Disconnect);
    Q_STATE_DECL(SendAT_SYSTORE);
    Q_STATE_DECL(ResetStart);
}; // class AO_ESP32C

} // namespace AO
//$enddecl${AOs::AO_ESP32C} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// callbacks
void AO_ESP32C_SocketDataReceiveCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id,  uint8_t* data, uint32_t length);
void AO_ESP32C_HotspotOpenCallback(AO::AO_ESP32C* caller, bool result);
void AO_ESP32C_HotspotClientConnectionCallback(AO::AO_ESP32C* caller, bool result);
void AO_ESP32C_HotspotClientDisconnectionCallback(AO::AO_ESP32C* caller, bool result);
void AO_ESP32C_SendDataCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id);
void AO_ESP32C_WifiConnectCallback(AO::AO_ESP32C* caller, bool result);
void AO_ESP32C_WifiDisconnectionCallback(AO::AO_ESP32C* caller, bool result);
void AO_ESP32C_TcpSocketOpenCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id);
void AO_ESP32C_UdpSocketOpenCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id);
void AO_ESP32C_TcpSocketCloseCallback(AO::AO_ESP32C* caller, bool result,  DRV::ESP32C3::LinkId socket_id);
void AO_ESP32C_ReadCompleteCallback(AO::AO_ESP32C* caller, bool result);
void AO_ESP32C_ConfigCompleteCallback(AO::AO_ESP32C* caller);
void AO_ESP32C_ServerOpenCallback(AO::AO_ESP32C* caller, bool result);
void AO_ESP32C_IpAssignedCallback(AO::AO_ESP32C* caller, bool result);
void AO_ESP32C_HotspotIpAssignedCallback(AO::AO_ESP32C* caller, bool result);
void AO_ESP32C_ServerTcpSocketOpen(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id);
void AO_ESP32C_WebSocketOpenCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id);
void AO_ESP32C_WebSocketCloseCallback(AO::AO_ESP32C* caller, bool result,  DRV::ESP32C3::LinkId socket_id);
void AO_ESP32C_WebSocketSendCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id);
void AO_ESP32C_WebSocketDataReceiveCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id,  uint8_t* data, uint32_t length);
void AO_ESP32C_TimeoutModuleUnresponsiveCallback(AO::AO_ESP32C* caller);
#endif // BSP_HPP
