//$file${.::AO_ESP32C.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: AO_ESP32C.qm
// File:  ${.::AO_ESP32C.cpp}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::AO_ESP32C.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#include "AO_ESP32C.hpp"
#include "Components.h"
#include "Debug_Print.hpp"

using namespace QP;
using namespace DRV;

// weak callbacks implementation
__attribute__((weak)) void AO_ESP32C_ConfigCompleteCallback(AO::AO_ESP32C* caller)
{ ;}
__attribute__((weak)) void AO_ESP32C_WifiConnectCallback(AO::AO_ESP32C* caller, bool result)
{ ;}
__attribute__((weak)) void AO_ESP32C_HotspotOpenCallback(AO::AO_ESP32C* caller, bool result)
{ ;}
__attribute__((weak)) void AO_ESP32C_TcpSocketOpenCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id)
{ ;}
__attribute__((weak)) void AO_ESP32C_UdpSocketOpenCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id)
{;}
__attribute__((weak)) void AO_ESP32C_ServerTcpSocketOpen(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id)
{ ;}
__attribute__((weak)) void AO_ESP32C_TcpSocketCloseCallback(AO::AO_ESP32C* caller, bool result,  DRV::ESP32C3::LinkId socket_id)
{ ;}
__attribute__((weak)) void AO_ESP32C_ReadCompleteCallback(AO::AO_ESP32C* caller, bool result)
{ ;}
__attribute__((weak)) void AO_ESP32C_ServerOpenCallback(AO::AO_ESP32C* caller, bool result)
{ ;}
__attribute__((weak)) void AO_ESP32C_SendDataCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id)
{;}
__attribute__((weak)) void AO_ESP32C_SocketDataReceiveCallback(AO::AO_ESP32C* caller, bool result,  DRV::ESP32C3::LinkId socket_id, uint8_t* data, uint32_t length)
{;}
__attribute__((weak)) void AO_ESP32C_HotspotClientConnectionCallback(AO::AO_ESP32C* caller, bool result)
{;}
__attribute__((weak)) void AO_ESP32C_HotspotClientDisconnectionCallback(AO::AO_ESP32C* caller, bool result)
{;}
__attribute__((weak)) void AO_ESP32C_WifiDisconnectionCallback(AO::AO_ESP32C* caller, bool result)
{;}
__attribute__((weak)) void AO_ESP32C_IpAssignedCallback(AO::AO_ESP32C* caller, bool result)
{;}
__attribute__((weak)) void AO_ESP32C_HotspotIpAssignedCallback(AO::AO_ESP32C* caller, bool result)
{;}
__attribute__((weak)) void AO_ESP32C_WebSocketOpenCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id)
{;}
__attribute__((weak)) void AO_ESP32C_WebSocketSendCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id)
{;}
__attribute__((weak)) void AO_ESP32C_TimeoutModuleUnresponsiveCallback(AO::AO_ESP32C* caller)
{;}
__attribute__((weak)) void AO_ESP32C_WebSocketCloseCallback(AO::AO_ESP32C* caller, bool result,  DRV::ESP32C3::LinkId socket_id)
{;}
__attribute__((weak)) void AO_ESP32C_WebSocketDataReceiveCallback(AO::AO_ESP32C* caller, bool result, DRV::ESP32C3::LinkId socket_id,  uint8_t* data, uint32_t length)
{;}

// opaque pointer to the Blinky active object --------------------------------
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::CloseSocketEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AO {

} // namespace AO
//$enddef${AOs::CloseSocketEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_ESP32C_StartEvent} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AO {

} // namespace AO
//$enddef${AOs::AO_ESP32C_StartEvent} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::AO_ESP32C} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace AO {

//${AOs::AO_ESP32C} ..........................................................

//${AOs::AO_ESP32C::AO_ESP32C} ...............................................
AO_ESP32C::AO_ESP32C(ESP32C_Init_t& _init)
  : QActive(Q_STATE_CAST(&AO_ESP32C::initial)),
    m_timeEvt(this, TIMEOUT_SIG, 0U),
    init(_init),
    m_unsolicitedTimeEvt(this, ESP32C_UNSOLICITED_TIMEOUT_SIG, 0U),
    m_incomingDataCheckTimeEvt(this, ESP32C_DATA_RECEIVE_CHECK_SIG, 0U),
    m_connectionCheckTimeEvt(this, ESP32C_CONNECTION_CHECK_SIG, 0U)

{}

//${AOs::AO_ESP32C::Begin} ...................................................
void AO_ESP32C::Begin(
    DRV::ESP32C3::WiFiMode _mode,
    void* caller)
{
    AO_ESP32C_StartEvent *evt = Q_NEW(AO_ESP32C_StartEvent, ESP32C_START_SIG);
    evt->mode = _mode;
    this->POST(evt,caller);
}

//${AOs::AO_ESP32C::ReceiveCompleteCallback} .................................
void AO_ESP32C::ReceiveCompleteCallback(
    DRV::ESP32C3::Event  event,
    DRV::ESP32C3*  caller,
    uint8_t*  data)
{
    // check event type
    if(event == DRV::ESP32C3::Event::RespReceived)
    {
        // copy data to buffer
        uint32_t len =strnlen((char*)data, sizeof(rx_buffer));
        if(len> sizeof(rx_buffer))
        {
            len = sizeof(rx_buffer);
        }
        memcpy(rx_buffer, data, len);
        rx_buffer[len] = 0;
        QP::QEvt *evt = Q_NEW(QP::QEvt, ESP32C_OK_SIG);
        this->POST(evt,caller);

    }else if( event == DRV::ESP32C3::Event::RespErr )
    {
        QP::QEvt *evt = Q_NEW(QP::QEvt, ESP32C_ERR_SIG);
        this->POST(evt,caller);
    }

}

//${AOs::AO_ESP32C::WiFiConnect} .............................................
void AO_ESP32C::WiFiConnect(
    const uint8_t* _ssid,
    const uint8_t* _pwd,
    void* caller)
{
    // copy wifi credential into the internal buffer
    strncpy((char*)ssid,(const char*)_ssid, sizeof(ssid));
    strncpy((char*)pwd ,(const char*)_pwd , sizeof(pwd));
    // send ESP32_CONNECT_WIFI_SIG
    #if !Q_UTEST  // in unit test mode just buffer the input parameters
        QEvt *evt = Q_NEW(QEvt, ESP32C_CONNECT_WIFI_SIG);
        this->POST(evt,caller);
    #else
    // do nothing
    #endif
}

//${AOs::AO_ESP32C::WiFiHotspotOpen} .........................................
void AO_ESP32C::WiFiHotspotOpen(
    const uint8_t* _ssid,
    const uint8_t* _pwd,
    DRV::ESP32C3::WifiChannelIds _channel_id,
    DRV::ESP32C3::WifiEncryption _encryption,
    uint8_t _max_conn,
    bool _hidden,
    void* caller)
{
    // copy hotspot settings into internal buffers
    strncpy((char*)hotspot_ssid,(const char*)_ssid, sizeof(hotspot_ssid));
    strncpy((char*)hotspot_pwd ,(const char*)_pwd , sizeof(hotspot_pwd));
    hotspot_channel_id = _channel_id;
    hotspot_encryption = _encryption;
    hotspot_hidden     = _hidden;
    hotspot_max_conn   = _max_conn;
    #if !Q_UTEST  // in unit test mode just buffer the input parameters
        // send ESP32C_HOTSPOT_CONF_SIG
        QEvt *evt = Q_NEW(QEvt, ESP32C_HOTSPOT_CONFIG_SIG);
        this->POST(evt,caller);
    #endif
}

//${AOs::AO_ESP32C::TcpOpenSocket} ...........................................
void AO_ESP32C::TcpOpenSocket(
    const uint8_t* address,
    uint16_t port,
    void* caller)
{
    if( address == nullptr || strnlen((char*)address, sizeof(remote_address))>= sizeof(remote_address))
    {
        TRACE_AO_ESP32C("TcpErrInput");
        AO_ESP32C_TcpSocketOpenCallback(this, false, client_link_id );
    }
    else{
        // create event
        OpenTcpSocketEvt *evt = Q_NEW(OpenTcpSocketEvt, ESP32C_TCP_CONNECT_SIG);
        evt->port = port;
        strncpy((char*)evt->address,(const char*)address, sizeof(remote_address));
    /* Send the ESP32C_TCP_CONNECT_SIG*/
    #if !Q_UTEST // in unit test mode just buffer the input parameters
        // send the event
        this->POST(evt,caller);
    #endif
    }
}

//${AOs::AO_ESP32C::SendData} ................................................
bool AO_ESP32C::SendData(
    const uint8_t* data,
    uint32_t length,
    DRV::ESP32C3::LinkId _socket_id,
    void* caller)
{
    bool retVal = true;
    if( length <= sizeof(send_data_buffer)
        && _socket_id< DRV::ESP32C3::LinkId::LinkIdMax
        && (socket_status[_socket_id] == ESP32C_SOCKET_STATUS_SERVER_OPEN
            || socket_status[_socket_id] == ESP32C_SOCKET_STATUS_OPEN))
    {

    #if !Q_UTEST // in unit test mode just buffer the input parameters
    /// EVENT CREATION
        SendDataEvt *evt = Q_NEW(SendDataEvt, ESP32C_SEND_DATA_SIG);
        memcpy(evt->data, data, length);
        evt->length = length;
        evt->socket_id = _socket_id;
        this->POST(evt,caller);
    ////
    #endif
    }else //<-- socket not opened OR size exceeded
    {
        TRACE_AO_ESP32C("SNDERR_%d_Sock%d", length, (uint8_t)socket_status[_socket_id]);
        retVal = false;
    #if !Q_UTEST
        AO_ESP32C_SendDataCallback(this, false, _socket_id);
    #endif
    }
    return retVal;
}

//${AOs::AO_ESP32C::ReadData} ................................................
void AO_ESP32C::ReadData(
    uint8_t* receive_buffer,
    uint32_t max_length,
    uint32_t timeout_ms,
    void* caller)
{
    receive_data_buffer_ptr = receive_buffer;
    receive_data_max_length = max_length;
    user_timeout_ms = timeout_ms;
    TRACE_AO_ESP32C("StartRead %d,%d", max_length, timeout_ms);
    #if !Q_UTEST // in unit test mode just buffer the input parameters
        // send ESP32C_HOTSPOT_CONF_SIG
        QEvt *evt = Q_NEW(QEvt, ESP32C_READ_DATA_SIG);
        this->POST(evt,caller);
    #endif
}

//${AOs::AO_ESP32C::TcpCloseSocket} ..........................................
void AO_ESP32C::TcpCloseSocket(
    DRV::ESP32C3::LinkId socket_id,
    void* caller)
{


    #if ! Q_UTEST
    // create event
        CloseSocketEvt *evt = Q_NEW(CloseSocketEvt, ESP32C_CLOSE_SOCKET_SIG);
        evt->socket_id = socket_id;
        this->POST(evt, this);
    #endif
}

//${AOs::AO_ESP32C::OpenServer} ..............................................
void AO_ESP32C::OpenServer(
    uint16_t port,
    void* caller,
    uint8_t _server_max_connections)
{
    // buffer server port
    server_port = port;
    server_max_connections = _server_max_connections;
    #if !Q_UTEST  // in unit test mode just buffer the input parameters
        // send ESP32C_OPEN_SERVER_SIG
        QEvt *evt = Q_NEW(QEvt, ESP32C_OPEN_SERVER_SIG);
        this->POST(evt,caller);
    #endif
}

//${AOs::AO_ESP32C::GetFreeSocketId} .........................................
uint8_t AO_ESP32C::GetFreeSocketId(DRV::ESP32C3::LinkId* startOutput_socketId) {
    uint8_t retVal = 0;
    for( uint8_t id = (uint8_t)(*startOutput_socketId);
         id<(uint8_t)DRV::ESP32C3::LinkIdMax;
         id++)
    {
        if(socket_status[id] == ESP32C_SOCKET_STATUS_CLOSE)
        {
            /* unopened socket found */
            retVal = 1;
            *startOutput_socketId = (DRV::ESP32C3::LinkId)id;
            TRACE_AO_ESP32C("GotId%d", id);
            break;
        }
    }

    if(!retVal)
    {
        TRACE_AO_ESP32C("ID_GET_FAI");
    }

    return retVal;
}

//${AOs::AO_ESP32C::GetFreeWsSocketId} .......................................
uint8_t AO_ESP32C::GetFreeWsSocketId(DRV::ESP32C3::LinkId* startOutput_socketId) {
    uint8_t retVal = 0;
    for( uint8_t id = (uint8_t)(*startOutput_socketId);
         id<ESP32C3_MAX_WS_SOCKET;
         id++)
    {
        if(socket_status[id] == ESP32C_SOCKET_STATUS_CLOSE)
        {
            /* unopened socket found */
            retVal = 1;
            *startOutput_socketId = (DRV::ESP32C3::LinkId)id;
            TRACE_AO_ESP32C("GotId%d", id);
            break;
        }
    }

    if(!retVal)
    {
        TRACE_AO_ESP32C("ID_GET_FAI");
    }

    return retVal;
}

//${AOs::AO_ESP32C::NotifyUnsolicitedMsgBegin} ...............................
void AO_ESP32C::NotifyUnsolicitedMsgBegin(void* caller) {
    #if !Q_UTEST // in unit test mode ignore
        // send ESP32C_UNSOLICITED_STA_SIG
        QEvt *evt = Q_NEW(QEvt, ESP32C_UNSOLICITED_STA_SIG);
        this->POST(evt,caller);
    #endif
}

//${AOs::AO_ESP32C::NotifyUnsolicitedMsgEnd} .................................
void AO_ESP32C::NotifyUnsolicitedMsgEnd(
    void* caller,
    DRV::ESP32C3::Event event,
    uint8_t* data)
{
    // copy data to buffer
    uint32_t len =strnlen((char*)data, sizeof(rx_buffer));
    if(len> sizeof(rx_buffer))
    {
        len = sizeof(rx_buffer);
    }
    memcpy(rx_buffer, data, len);
    rx_buffer[len] = 0;
    #if !Q_UTEST // in unit test mode ignore
        // send ESP32C_UNSOLICITED_STA_SIG
        QEvt *evt = Q_NEW(QEvt, ESP32C_UNSOLICITED_END_SIG);
        this->POST(evt,caller);
    #endif
}

//${AOs::AO_ESP32C::WebSocket_Open} ..........................................
bool AO_ESP32C::WebSocket_Open(
    uint32_t _ws_ping_interval_s,
    uint32_t _ws_ping_timeout_s,
    uint8_t* _ws_header,
    uint16_t _ws_header_len,
    uint8_t* _ws_uri,
    uint16_t _ws_uri_len,
    const uint8_t* _ws_sub_protocol,
    uint16_t _ws_sub_protocol_len,
    const uint8_t* _ws_auth,
    uint16_t _ws_auth_len,
    void* caller)
{
    bool retVal = true;
    TRACE_AO_ESP32C("WsOpnReq");
    if(_ws_header_len <= sizeof(ws_header)
       && _ws_uri_len <= sizeof(ws_uri)
       && _ws_uri != nullptr
       && _ws_uri_len>0)
    {
    ///
        OpenWsSocketEvt *evt = Q_NEW(OpenWsSocketEvt, ESP32C_WEBSOCKET_OPEN_SIG);
        evt->ws_uri_len = _ws_uri_len;
        memcpy(evt->ws_uri, _ws_uri, _ws_uri_len);
        evt->ws_ping_timeout_s = _ws_ping_timeout_s;
        evt->ws_ping_interval_s = _ws_ping_interval_s;
        evt->ws_header_len = _ws_header_len;
        memcpy(evt->ws_header, _ws_header, _ws_header_len);
        evt->ws_auth_len = _ws_auth_len;
        memcpy(evt->ws_auth, _ws_auth, _ws_auth_len);
        evt->ws_sub_protocol_len = _ws_sub_protocol_len;
        memcpy(evt->ws_sub_protocol, _ws_sub_protocol, _ws_sub_protocol_len);
    ///
        /* Send the ESP32C_WEBSOCKET_OPEN signal*/
        #if !Q_UTEST // in unit test mode just buffer the input parameters
            // send ESP32C_WEBSOCKET_OPEN
            this->POST(evt,caller);
        #endif
    ///

    }else
    {
       TRACE_AO_ESP32C("WSHDRLenErr%d", _ws_header_len);
       retVal = false;
       AO_ESP32C_WebSocketOpenCallback(this, false, DRV::ESP32C3::LinkIdInvalid);
    }
    return retVal;
}

//${AOs::AO_ESP32C::WebSocket_SendData} ......................................
bool AO_ESP32C::WebSocket_SendData(
    const uint8_t* data,
    uint32_t length,
    DRV::ESP32C3::LinkId _socket_id,
    DRV::ESP32C3::WebSockedtOpCode_t _ws_opcode,
    void* caller)
{
    bool retVal = true;
    if( length <= sizeof(send_data_buffer)
        && socket_status[_socket_id] == ESP32C_SOCKET_STATUS_WS_OPEN )
    {

    #if !Q_UTEST // in unit test mode just buffer the input parameters

        SendDataEvt *evt = Q_NEW(SendDataEvt, ESP32C_WEBSOCKET_SEND_DATA_SIG);
        memcpy(evt->data, data, length);
        evt->length = length;
        evt->socket_id = _socket_id;
        evt->opcode = _ws_opcode;
        this->POST(evt,caller);

    #endif
    }else //<-- socket not opened OR size exceeded
    {
        TRACE_AO_ESP32C("WS_SNDERR_%d_Sock%d", length, (uint8_t)socket_status[_socket_id]);
        retVal = false;
    #if !Q_UTEST
        AO_ESP32C_WebSocketSendCallback(this, false, _socket_id);
    #endif
    }
    return retVal;
}

//${AOs::AO_ESP32C::WebSocket_SendData} ......................................
bool AO_ESP32C::WebSocket_SendData(
    const uint8_t* data,
    uint32_t length,
    DRV::ESP32C3::LinkId _socket_id,
    DRV::ESP32C3::WebSockedtOpCode_t _ws_opcode,
    void* caller,
    uint8_t delayTicks)
{
    #ifdef QXK_HPP_ //this api only works with QXK

    for (int i = 0; i<5;i++)
    {
        if(false == idle_flag)
        {
            QP::QXThread::delay(delayTicks);
        }else{
            return WebSocket_SendData(data, length,_socket_id, _ws_opcode, caller);
        }

    }

    #endif
    return false;
}

//${AOs::AO_ESP32C::WebSocket_Close} .........................................
bool AO_ESP32C::WebSocket_Close(
    DRV::ESP32C3::LinkId socket_id,
    void* caller)
{

    /* Create and send the ESP32C_WEBSOCKET_CLOSE*/
    #if !Q_UTEST // in unit test mode just buffer the input parameters
        CloseSocketEvt *evt = Q_NEW(CloseSocketEvt, ESP32C_WEBSOCKET_CLOSE_SIG);
        evt->socket_id = socket_id;
        this->POST(evt,caller);
    #endif
    return true;
}

//${AOs::AO_ESP32C::NotifyUnsolicitedMsgCont} ................................
void AO_ESP32C::NotifyUnsolicitedMsgCont(void* caller) {
    m_unsolicitedTimeEvt.rearm(ESP32C_UNSOLICITED_TIMEOUT_MS);
}

//${AOs::AO_ESP32C::UdpOpen} .................................................
bool AO_ESP32C::UdpOpen(
    uint8_t _local_port,
    uint8_t _remote_port,
    const uint8_t* address,
    void* caller)
{
    udp_local_port = _local_port;
    udp_remote_port = _remote_port;

    /* buffer address and port internally*/
    strncpy((char*)remote_address,(const char*)address, sizeof(remote_address));

    /* Send the ESP32C_TCP_CONNECT_SIG*/
    #if !Q_UTEST // in unit test mode just buffer the input parameters
        // send ESP32C_HOTSPOT_CONF_SIG
        QEvt *evt = Q_NEW(QEvt, ESP32C_UDP_CONNECT_SIG);
        this->POST(evt,caller);
    #endif
}

//${AOs::AO_ESP32C::SM} ......................................................
Q_STATE_DEF(AO_ESP32C, initial) {
    //${AOs::AO_ESP32C::SM::initial}
    // arm the private time event to expire in 1/2s

    (void)e; // unused parameter

    QS_FUN_DICTIONARY(&AO_ESP32C::InitState);
    QS_FUN_DICTIONARY(&AO_ESP32C::offState);
    QS_FUN_DICTIONARY(&AO_ESP32C::Idle_ConfiguredState);
    QS_FUN_DICTIONARY(&AO_ESP32C::HotspotConfigurationState);
    QS_FUN_DICTIONARY(&AO_ESP32C::Parse_CWSAP_Response);
    QS_FUN_DICTIONARY(&AO_ESP32C::SEND_AT_CWSAP);
    QS_FUN_DICTIONARY(&AO_ESP32C::WiFi_ConfigState);
    QS_FUN_DICTIONARY(&AO_ESP32C::Send_AT_CWJAP);
    QS_FUN_DICTIONARY(&AO_ESP32C::Parse_CWJAP_Response);
    QS_FUN_DICTIONARY(&AO_ESP32C::Idle_NetworkConnectedState);
    QS_FUN_DICTIONARY(&AO_ESP32C::Busy_NetworkConnectedState);
    QS_FUN_DICTIONARY(&AO_ESP32C::CloseTCPSocketState);
    QS_FUN_DICTIONARY(&AO_ESP32C::OpenTCPSocketState);
    QS_FUN_DICTIONARY(&AO_ESP32C::TransmitDataState);
    QS_FUN_DICTIONARY(&AO_ESP32C::InitiateSendDataState);
    QS_FUN_DICTIONARY(&AO_ESP32C::WaitingForDataState);
    QS_FUN_DICTIONARY(&AO_ESP32C::WebSocket_OpenState);
    QS_FUN_DICTIONARY(&AO_ESP32C::Send_AT_WSCFG);
    QS_FUN_DICTIONARY(&AO_ESP32C::Send_AT_WSHEAD);
    QS_FUN_DICTIONARY(&AO_ESP32C::Send_AT_WSOPEN);
    QS_FUN_DICTIONARY(&AO_ESP32C::Send_Header);
    QS_FUN_DICTIONARY(&AO_ESP32C::Websocket_SendState);
    QS_FUN_DICTIONARY(&AO_ESP32C::WebSocket_CloseState);
    QS_FUN_DICTIONARY(&AO_ESP32C::TransmitWebSocketDataState);
    QS_FUN_DICTIONARY(&AO_ESP32C::CreateServerState);
    QS_FUN_DICTIONARY(&AO_ESP32C::open_server);
    QS_FUN_DICTIONARY(&AO_ESP32C::UdpListenCommandState);
    QS_FUN_DICTIONARY(&AO_ESP32C::ConnectionCheckState);
    QS_FUN_DICTIONARY(&AO_ESP32C::Base_ConfigState);
    QS_FUN_DICTIONARY(&AO_ESP32C::SendAT);
    QS_FUN_DICTIONARY(&AO_ESP32C::SetMode);
    QS_FUN_DICTIONARY(&AO_ESP32C::ResetEnd);
    QS_FUN_DICTIONARY(&AO_ESP32C::SendCIPMUX);
    QS_FUN_DICTIONARY(&AO_ESP32C::Disconnect);
    QS_FUN_DICTIONARY(&AO_ESP32C::SendAT_SYSTORE);
    QS_FUN_DICTIONARY(&AO_ESP32C::ResetStart);

    return tran(&offState);
}

//${AOs::AO_ESP32C::SM::InitState} ...........................................
Q_STATE_DEF(AO_ESP32C, InitState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::ESP32C_START}
        case ESP32C_START_SIG: {
            const AO_ESP32C_StartEvent* _evt = Q_EVT_CAST(AO_ESP32C_StartEvent);
            this->mode = _evt->mode;
            TRACE_AO_ESP32C("START%d", (uint8_t)this->mode);
            status_ = tran(&Base_ConfigState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::TIMEOUT}
        case TIMEOUT_SIG: {
            timeout_counter++;
            #if !Q_UTEST
               TRACE_AO_ESP32C("Generic T/O");
               QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
               this->POST(evt,this);

            #endif
            //${AOs::AO_ESP32C::SM::InitState::TIMEOUT::[timeout_counter_exceeded]}
            if (timeout_counter> ESP32C_TIMEOUT_COUNT_MAX) {
                TRACE_AO_ESP32C("MODULE UNRESPONSIVE T/O");
                AO_ESP32C_TimeoutModuleUnresponsiveCallback(this);
                status_ = Q_RET_HANDLED;
            }
            else {
                status_ = Q_RET_UNHANDLED;
            }
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::ESP32C_UNSOLICITED_END}
        case ESP32C_UNSOLICITED_END_SIG: {
            m_unsolicitedTimeEvt.disarm();
            uint32_t token_length = 0;
            init.esp->GetRxBufferData(rx_buffer, sizeof(rx_buffer));
            ESP32C3::UnsolicitedMessage type = init.esp->GetUnsolicitedMessage(rx_buffer, &token_length);
            unsolicited_msg_flag = false;
            if(type == ESP32C3::IPD)
            {
                uint32_t len = 0;

                ESP32C3::LinkId socket;
                uint8_t* ipdStart = nullptr;
                uint8_t* data = init.esp->GetIPD(rx_buffer,&ipdStart, &len,sizeof(rx_buffer), &socket);
                TRACE_AO_ESP32C("DataRcvd,%d,%d", (uint8_t)socket, len);
                if(data!= nullptr)
                {
                   AO_ESP32C_SocketDataReceiveCallback(this, true , socket, data, len);
                }
            }else{
                TRACE_AO_ESP32C("RecvdUnsol%d", (uint8_t)type);
            }
            init.esp->FlushRx();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::ESP32C_UNSOLICITED_STA}
        case ESP32C_UNSOLICITED_STA_SIG: {
            m_unsolicitedTimeEvt.disarm();
            unsolicited_msg_flag = true;
            m_unsolicitedTimeEvt.armX( ESP32C_UNSOLICITED_TIMEOUT_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::ESP32C_UNSOLICITED_TIMEOUT}
        case ESP32C_UNSOLICITED_TIMEOUT_SIG: {
            m_unsolicitedTimeEvt.disarm();
            unsolicited_msg_flag = false;
            uint8_t parse_limit = 10;
            uint32_t token_length = 0;
            uint32_t offset = 0;
            init.esp->GetRxBufferData(rx_buffer, sizeof(rx_buffer));
            ESP32C3::UnsolicitedMessage type = init.esp->GetUnsolicitedMessage(rx_buffer, &token_length);
            while(ESP32C3::UnsolicitedMessage::Unknown != type && parse_limit!=0)
            {
                if(type == ESP32C3::IPD)
                {
                    uint32_t len = 0;

                    ESP32C3::LinkId socket;

                    uint8_t* ipdStart = nullptr;
                    uint8_t* data = init.esp->GetIPD(rx_buffer,&ipdStart, &len, sizeof(rx_buffer), &socket);
                    token_length+= ipdStart-rx_buffer;
                    TRACE_AO_ESP32C("DataRcvd,%d,%d", (uint8_t)socket, len);
                    if(data!= nullptr)
                    {
                       AO_ESP32C_SocketDataReceiveCallback(this, true , socket, data, len);
                    }
                }
                else if(type == ESP32C3::WebSocketData)
                {
                    uint32_t len = 0;

                    ESP32C3::LinkId socket;

                    uint8_t* wsDataStart = nullptr;
                    uint8_t* data = init.esp->GetWsData(rx_buffer,&wsDataStart, &len, sizeof(rx_buffer), &socket);
                    token_length+= wsDataStart-rx_buffer;
                    TRACE_AO_ESP32C("WSDataRcvd,%d,%d", (uint8_t)socket, len);
                    if(data!= nullptr)
                    {
                       AO_ESP32C_WebSocketDataReceiveCallback(this, true , socket, data, len);
                    }
                }
                else if(type == DRV::ESP32C3::SocketConnection )
                {

                   ESP32C3::LinkId id;
                   bool parseResult = init.esp->GetClientConnectionId(rx_buffer, &id);
                   TRACE_AO_ESP32C("conn%d", (uint8_t)id);
                   if(parseResult){

                      socket_status[id] = ESP32C_SOCKET_STATUS_SERVER_OPEN;
                      AO_ESP32C_ServerTcpSocketOpen(this, true, id);
                   }
                }
                else if(type == DRV::ESP32C3::SocketClose )
                {

                   ESP32C3::LinkId id;
                   bool parseResult = init.esp->GetClientConnectionId(rx_buffer, &id);
                   TRACE_AO_ESP32C("CliDisconn%d", (uint8_t)id);
                   if(parseResult){
                      socket_status[id] = ESP32C_SOCKET_STATUS_CLOSE;
                   }
                }
                else if(type == DRV::ESP32C3::WifiClientConnection )
                {

                   AO_ESP32C_HotspotClientConnectionCallback(this, true);
                }
                else if(type == DRV::ESP32C3::WifiClientDisconnection )
                {

                   /*scan for sockets that used that connection todo this needs to be reworked if we use local lan connectivity*/
                   for(int i = 0; i< DRV::ESP32C3::LinkIdMax; i++)
                   {
                       /* manually close the socket since esp32 does not do that automatically*/
                       if(socket_status[i] == ESP32C_SOCKET_STATUS_SERVER_OPEN )
                       {
                           TcpCloseSocket((DRV::ESP32C3::LinkId)i, this);
                       }
                   }
                   AO_ESP32C_HotspotClientDisconnectionCallback(this, true);

                }
                else if(type == DRV::ESP32C3::WifiDisconnection )
                {

                   TRACE_AO_ESP32C("WifiAPDisconn");

                   AO_ESP32C_WifiDisconnectionCallback(this, true);
                }
                else if(type == DRV::ESP32C3::WifiConnection )
                {

                   TRACE_AO_ESP32C("WifiConn");
                   AO_ESP32C_WifiConnectCallback(this, true);
                }
                else if(type == DRV::ESP32C3::IpAssignment )
                {

                   TRACE_AO_ESP32C("IpAss");
                   AO_ESP32C_IpAssignedCallback(this, true);
                }
                else if(type == DRV::ESP32C3::WifiIpClient )
                {

                   TRACE_AO_ESP32C("HotspotIpAss");
                   AO_ESP32C_HotspotIpAssignedCallback(this, true);
                }
                else if(type == DRV::ESP32C3::WebsocketConnect)
                {
                   ESP32C3::LinkId id;

                   bool parseResult = init.esp->GetWsClientConnectionId(rx_buffer, &id);
                   TRACE_AO_ESP32C("WsCliConn%d", (uint8_t)id);
                }
                else if(type == DRV::ESP32C3::WebsocketDisconnect)
                {
                   ESP32C3::LinkId id;

                   bool parseResult = init.esp->GetWsClientDisconnectionId(rx_buffer, &id);
                   TRACE_AO_ESP32C("WsCliDisconn%d", (uint8_t)id);
                   if(parseResult)
                   {
                      socket_status[id] = ESP32C_SOCKET_STATUS_CLOSE;
                      AO_ESP32C_WebSocketCloseCallback(this, true,  id);
                   }
                }
                else if(type == DRV::ESP32C3::WebsocketClosed)
                {
                   ESP32C3::LinkId id;

                   bool parseResult = init.esp->GetWsClientClosedId(rx_buffer, &id);
                   TRACE_AO_ESP32C("WsCliClosed%d", (uint8_t)id);
                   if(parseResult)
                   {
                      socket_status[id] = ESP32C_SOCKET_STATUS_CLOSE;
                      AO_ESP32C_WebSocketCloseCallback(this, true,  id);

                   }
                }
                else{
                    break;
                    TRACE_AO_ESP32C("RecvdUnsol%d", (uint8_t)type);
                }
                // decresease parse limit counter to forbid infinite loops
                parse_limit--;
                // increase parsing offset
                offset += token_length;
                // advance and parse again
                type = init.esp->GetUnsolicitedMessage(rx_buffer+offset, &token_length);
            }//while loop
            memset(rx_buffer, 0, sizeof(rx_buffer));
            // Flush received data
            init.esp->FlushRx();

            TRACE_AO_ESP32C("UnsolicitedEnd");
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::offState} .................................
Q_STATE_DEF(AO_ESP32C, offState) {
    QP::QState status_;
    switch (e->sig) {
        default: {
            status_ = super(&InitState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredState} .....................
Q_STATE_DEF(AO_ESP32C, Idle_ConfiguredState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredState}
        case Q_ENTRY_SIG: {

            TRACE_AO_ESP32C("IDLECONFENTR");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::ESP32C_HOTSPOT_CONFIG}
        case ESP32C_HOTSPOT_CONFIG_SIG: {
            status_ = tran(&HotspotConfigurationState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::ESP32C_CONNECT_WIFI}
        case ESP32C_CONNECT_WIFI_SIG: {
            status_ = tran(&WiFi_ConfigState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::ESP32C_WEBSOCKET_SEND_DATA}
        case ESP32C_WEBSOCKET_SEND_DATA_SIG: {
            if(init.deferQueue->getNFree()>0)
            {
                this->defer(init.deferQueue, e);
                TRACE_AO_ESP32C("WsSendDeferred");
            }
            else
            {
                TRACE_AO_ESP32C("LostWsSend");
            }

            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::ESP32C_SEND_DATA}
        case ESP32C_SEND_DATA_SIG: {
            if(init.deferQueue->getNFree()>0)
            {
                this->defer(init.deferQueue, e);
                TRACE_AO_ESP32C("SendDeferred");
            }
            else
            {
                TRACE_AO_ESP32C("LostSend");
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::ESP32C_CONNECTION_CHECK}
        case ESP32C_CONNECTION_CHECK_SIG: {
            if(init.deferQueue->getNFree()>0)
            {
                this->defer(init.deferQueue, e);
                TRACE_AO_ESP32C("ConnChkDef");
            }
            else
            {
                TRACE_AO_ESP32C("LostConnChk");
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&InitState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigurationState}
Q_STATE_DEF(AO_ESP32C, HotspotConfigurationState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigurationState}
        case Q_ENTRY_SIG: {
            error_counter = 0;
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigurationState}
        case Q_EXIT_SIG: {
            error_counter = 0;
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigura~::initial}
        case Q_INIT_SIG: {
            status_ = tran(&SEND_AT_CWSAP);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigura~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            error_counter++;
            m_timeEvt.disarm();
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigura~::ESP32C_ERR::[error_counter<ESP32C_RETRY_MAX]}
            if (error_counter<ESP32C_RETRY_MAX) {
                status_ = tran(&SEND_AT_CWSAP);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigura~::ESP32C_ERR::[else]}
            else {
                AO_ESP32C_WifiConnectCallback(this, false);
                status_ = tran(&Idle_ConfiguredState);
            }
            break;
        }
        default: {
            status_ = super(&Idle_ConfiguredState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigura~::Parse_CWSAP_Response}
Q_STATE_DEF(AO_ESP32C, Parse_CWSAP_Response) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigura~::Parse_CWSAP_Response}
        case Q_ENTRY_SIG: {
            #if !Q_UTEST
                if(init.esp->Parse_AT_CWSAP())
                {
                   QEvt *evt = Q_NEW(QEvt, ESP32C_OK_SIG);
                   this->POST(evt,this);
                }else{
                   QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
                   this->POST(evt,this);
                }
            #endif
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigura~::Parse_CWSAP_Resp~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            hotspot_active = true;
            AO_ESP32C_HotspotOpenCallback(this, true);
            timeout_counter = 0;
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        default: {
            status_ = super(&HotspotConfigurationState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigura~::SEND_AT_CWSAP}
Q_STATE_DEF(AO_ESP32C, SEND_AT_CWSAP) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigura~::SEND_AT_CWSAP}
        case Q_ENTRY_SIG: {
            init.esp->Send_AT_CWSAP(
                hotspot_ssid,
                hotspot_pwd,
                hotspot_channel_id,
                hotspot_encryption,
                hotspot_max_conn,
                hotspot_hidden);

            m_timeEvt.armX( ESP32C_WIFI_CONN_INTERVAL_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::HotspotConfigura~::SEND_AT_CWSAP::ESP32C_OK}
        case ESP32C_OK_SIG: {
            m_timeEvt.disarm();
            status_ = tran(&Parse_CWSAP_Response);
            break;
        }
        default: {
            status_ = super(&HotspotConfigurationState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState} ......
Q_STATE_DEF(AO_ESP32C, WiFi_ConfigState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState}
        case Q_ENTRY_SIG: {
            error_counter = 0;
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState}
        case Q_EXIT_SIG: {
            error_counter = 0;
            m_timeEvt.disarm();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState::initial}
        case Q_INIT_SIG: {
            status_ = tran(&Send_AT_CWJAP);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            error_counter++;
            TRACE_AO_ESP32C("WifiConnErr_%d", error_counter);
            m_timeEvt.disarm();
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState::ESP32C_ERR::[error_counter<ESP32C_RETRY_MAX]}
            if (error_counter<ESP32C_RETRY_MAX) {
                TRACE_AO_ESP32C("Retry");
                status_ = tran(&Send_AT_CWJAP);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState::ESP32C_ERR::[else]}
            else {
                TRACE_AO_ESP32C("ConnRetriesExceed");

                AO_ESP32C_WifiConnectCallback(this, false);
                status_ = tran(&Idle_NetworkConnectedState);
            }
            break;
        }
        default: {
            status_ = super(&Idle_ConfiguredState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState::Send_AT_CWJAP}
Q_STATE_DEF(AO_ESP32C, Send_AT_CWJAP) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState::Send_AT_CWJAP}
        case Q_ENTRY_SIG: {
            init.esp->Send_AT_CWJAP(ssid,pwd);
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_WIFI_CONN_INTERVAL_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState::Send_AT_CWJAP::ESP32C_OK}
        case ESP32C_OK_SIG: {
            m_timeEvt.disarm();
            timeout_counter = 0;
            status_ = tran(&Parse_CWJAP_Response);
            break;
        }
        default: {
            status_ = super(&WiFi_ConfigState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState::Parse_CWJAP_Response}
Q_STATE_DEF(AO_ESP32C, Parse_CWJAP_Response) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState::Parse_CWJAP_Response}
        case Q_ENTRY_SIG: {
            #if !Q_UTEST
                if(init.esp->Parse_AT_CWJAP())
                {
                   QEvt *evt = Q_NEW(QEvt, ESP32C_OK_SIG);
                   this->POST(evt,this);
                }else{
                   QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
                   this->POST(evt,this);
                }
            #endif
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::WiFi_ConfigState::Parse_CWJAP_Resp~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            timeout_counter = 0;
            m_connectionCheckTimeEvt.disarm();
            m_connectionCheckTimeEvt.armX( ESP32C_AO_CONNECTION_CHECK_PERIOD_MS,
                            0);
            AO_ESP32C_WifiConnectCallback(this, true);

            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        default: {
            status_ = super(&WiFi_ConfigState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConnectedState}
Q_STATE_DEF(AO_ESP32C, Idle_NetworkConnectedState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConnectedState}
        case Q_ENTRY_SIG: {
            init.esp->FlushRx();
            error_counter = 0;
            bool recalled = this->recall(init.deferQueue);
            idle_flag = true;
            if(recalled)
            {
               // recal deferred events
               TRACE_AO_ESP32C("RecallingEvt");
            }


            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConnectedState}
        case Q_EXIT_SIG: {
            idle_flag = false;
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConn~::ESP32C_TCP_CONNECT}
        case ESP32C_TCP_CONNECT_SIG: {
            error_counter = 0;
            client_link_id = DRV::ESP32C3::LinkId0;
            TRACE_AO_ESP32C("StaTcpReq@%s", (const char*)Q_EVT_CAST(OpenTcpSocketEvt)->address);
            /* buffer address and port internally*/
            strncpy((char*)remote_address,
                    (const char*)Q_EVT_CAST(OpenTcpSocketEvt)->address,
                    sizeof(remote_address));
            remote_port = Q_EVT_CAST(OpenTcpSocketEvt)->port;
            status_ = tran(&OpenTCPSocketState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConn~::ESP32C_OPEN_SERVER}
        case ESP32C_OPEN_SERVER_SIG: {
            status_ = tran(&CreateServerState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConn~::ESP32C_WEBSOCKET_OPEN}
        case ESP32C_WEBSOCKET_OPEN_SIG: {
            error_counter = 0;
            client_link_id = DRV::ESP32C3::LinkId0;

            /* buffer header internally*/
            ws_header_len =      Q_EVT_CAST(OpenWsSocketEvt)->ws_header_len;
            ws_sub_protocol_len = Q_EVT_CAST(OpenWsSocketEvt)->ws_sub_protocol_len;
            ws_auth_len =     Q_EVT_CAST(OpenWsSocketEvt)->ws_auth_len;
            ws_uri_len =         Q_EVT_CAST(OpenWsSocketEvt)->ws_uri_len;
            ws_ping_interval_s = Q_EVT_CAST(OpenWsSocketEvt)->ws_ping_interval_s;
            ws_ping_timeout_s =  Q_EVT_CAST(OpenWsSocketEvt)->ws_ping_timeout_s;
            // heaqder may or may not be required
            if(ws_header_len>0)
            {
                memset(ws_header, 0x0, sizeof(ws_header));
                memcpy((char*)ws_header,
                       (const char*)Q_EVT_CAST(OpenWsSocketEvt)->ws_header,
                       ws_header_len);
            }
            else
            {
                ws_header_len = 0;
            }
            if( ws_sub_protocol_len >0 &&  ws_sub_protocol_len< sizeof(ws_sub_protocol))
            {
                memset(ws_sub_protocol, 0x0, sizeof(ws_sub_protocol));
                memcpy(ws_sub_protocol,
                       Q_EVT_CAST(OpenWsSocketEvt)->ws_sub_protocol,
                       ws_sub_protocol_len);
            }
            else
            {
                TRACE_AO_ESP32C("NoSubProt");
                ws_sub_protocol_len = 0;
            }

            if( ws_auth_len >0 &&  ws_auth_len< sizeof(ws_auth))
            {
                memset(ws_auth, 0x0, sizeof(ws_auth));
                memcpy(ws_auth, Q_EVT_CAST(OpenWsSocketEvt)->ws_auth, ws_auth_len);
            }
            else
            {
                TRACE_AO_ESP32C("NoAuth");
                ws_auth_len = 0;
            }

            memset(ws_uri, 0x0, sizeof(ws_uri));
            memcpy((char*)ws_uri,
                        (const char*)Q_EVT_CAST(OpenWsSocketEvt)->ws_uri,
                         ws_uri_len);
            status_ = tran(&Send_AT_WSCFG);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConn~::ESP32C_SEND_DATA}
        case ESP32C_SEND_DATA_SIG: {

            // clean the tx buffer
            memset(send_data_buffer, 0, sizeof(send_data_buffer));
            // get send data info from the event
            memcpy(send_data_buffer, Q_EVT_CAST(SendDataEvt)->data, Q_EVT_CAST(SendDataEvt)->length);
            send_data_length = Q_EVT_CAST(SendDataEvt)->length;
            client_link_id = Q_EVT_CAST(SendDataEvt)->socket_id;
            // reset error counter
            error_counter = 0;
            // reset api result buffer
            commandParseResult = false;
            // start timeout timer
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_TCP_INTERVAL_MS,
                            0);
            // prepare for transmission
            init.esp->Send_AT_CIPSEND(client_link_id, send_data_length);


            status_ = tran(&InitiateSendDataState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConn~::ESP32C_READ_DATA}
        case ESP32C_READ_DATA_SIG: {
            status_ = tran(&WaitingForDataState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConn~::ESP32C_WEBSOCKET_SEND_DATA}
        case ESP32C_WEBSOCKET_SEND_DATA_SIG: {
            // clean the tx buffer
            memset(send_data_buffer, 0, sizeof(send_data_buffer));
            // get send data info from the event
            memcpy(send_data_buffer, Q_EVT_CAST(SendDataEvt)->data, Q_EVT_CAST(SendDataEvt)->length);
            send_data_length = Q_EVT_CAST(SendDataEvt)->length;

            ws_opcode = Q_EVT_CAST(SendDataEvt)->opcode;;
            client_link_id = Q_EVT_CAST(SendDataEvt)->socket_id;
            // reset error counter
            error_counter = 0;
            // reset command parse result
            commandParseResult = false;
            // start timeout timer
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_WS_INTERVAL_MS,
                            0);
            // prepare for transmission
            init.esp->Send_AT_WSSEND(client_link_id, send_data_length, ws_opcode);
            status_ = tran(&Websocket_SendState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConn~::ESP32C_WEBSOCKET_CLOSE}
        case ESP32C_WEBSOCKET_CLOSE_SIG: {
            DRV::ESP32C3::LinkId socket =
                Q_EVT_CAST(CloseSocketEvt)->socket_id;
            client_close_id = socket;

            // reset api result buffer
            commandParseResult = false;
            // start timeout timer
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_WS_INTERVAL_MS,
                            0);
            // close socket command
            init.esp->Send_AT_WSCLOSE(client_close_id);

            status_ = tran(&WebSocket_CloseState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConn~::ESP32C_CLOSE_SOCKET}
        case ESP32C_CLOSE_SOCKET_SIG: {
            DRV::ESP32C3::LinkId socket =
                Q_EVT_CAST(CloseSocketEvt)->socket_id;
            client_close_id = socket;

            // reset api result buffer
            commandParseResult = false;
            // start timeout timer
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_WIFI_CONN_INTERVAL_MS,
                            0);
            // close socket command
            init.esp->Send_AT_CIPCLOSE(client_close_id);
            status_ = tran(&CloseTCPSocketState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConn~::ESP32C_UDP_CONNECT}
        case ESP32C_UDP_CONNECT_SIG: {
            status_ = tran(&UdpListenCommandState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Idle_NetworkConn~::ESP32C_CONNECTION_CHECK}
        case ESP32C_CONNECTION_CHECK_SIG: {
            // reset api result buffer
            commandParseResult = false;
            // start timeout timer
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_WS_INTERVAL_MS,
                            0);
            // close socket command
            init.esp->Send_AT_CWSTATE();
            status_ = tran(&ConnectionCheckState);
            break;
        }
        default: {
            status_ = super(&Idle_ConfiguredState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConnectedState}
Q_STATE_DEF(AO_ESP32C, Busy_NetworkConnectedState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::ESP32C_CONNECT_WIFI}
        case ESP32C_CONNECT_WIFI_SIG: {
            if(init.deferQueue->getNFree()>0)
            {
                this->defer(init.deferQueue, e);
                TRACE_AO_ESP32C("ApConnectDeferred");
            }
            else
            {
                TRACE_AO_ESP32C("LostApConnect");
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&Idle_ConfiguredState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CloseTCPSocketState}
Q_STATE_DEF(AO_ESP32C, CloseTCPSocketState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CloseTCPSocketState}
        case Q_EXIT_SIG: {
            m_timeEvt.disarm();
            socket_status[client_close_id] = ESP32C_SOCKET_STATUS_CLOSE;
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CloseTCPSocketSt~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            AO_ESP32C_TcpSocketCloseCallback(this, false,  client_close_id);
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CloseTCPSocketSt~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            AO_ESP32C_TcpSocketCloseCallback(this, true,  client_close_id);
            timeout_counter = 0;
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::OpenTCPSocketState}
Q_STATE_DEF(AO_ESP32C, OpenTCPSocketState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::OpenTCPSocketState}
        case Q_ENTRY_SIG: {
            commandParseResult = false;
            /* see if there is a free link id (socket id)*/
            if(GetFreeSocketId(&client_link_id))
            {
                /* issue the at+cip start command */
                init.esp->Send_AT_CIPSTART(client_link_id,
                                     DRV::ESP32C3::TCP,
                                     (uint8_t*)remote_address,
                                     remote_port);
                m_timeEvt.disarm();
                m_timeEvt.armX( ESP32C_TCP_INTERVAL_MS,
                                0);
            }else{
               /* dispatch err sig*/
            #if !Q_UTEST

               QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
               this->POST(evt,this);

            #endif
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::OpenTCPSocketState}
        case Q_EXIT_SIG: {
            m_timeEvt.disarm();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::OpenTCPSocketSta~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {

            TRACE_AO_ESP32C("TcpE,Link%d", (uint8_t)client_link_id);
            // next retry, use a different link id
            client_link_id =
                                static_cast<DRV::ESP32C3::LinkId>((
                                (uint8_t)client_link_id+1)%
                                (uint8_t)DRV::ESP32C3::LinkIdMax);
            // increase error counter
            error_counter++;
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::OpenTCPSocketSta~::ESP32C_ERR::[retries_available]}
            if (error_counter<ESP32C_RETRY_MAX) {
                status_ = tran(&OpenTCPSocketState);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::OpenTCPSocketSta~::ESP32C_ERR::[else]}
            else {
                AO_ESP32C_TcpSocketOpenCallback(this, false, client_link_id);
                client_link_id = DRV::ESP32C3::LinkId0;
                status_ = tran(&Idle_NetworkConnectedState);
            }
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::OpenTCPSocketSta~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            #if !Q_UTEST
                commandParseResult = init.esp->Parse_AT_CIPSTART();
            #else
                commandParseResult = true;
            #endif
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::OpenTCPSocketSta~::ESP32C_OK::[commandsuccessful]}
            if (true == commandParseResult) {
                socket_status[client_link_id] = ESP32C_SOCKET_STATUS_OPEN;
                timeout_counter = 0;
                AO_ESP32C_TcpSocketOpenCallback(this, true, client_link_id );
                status_ = tran(&Idle_NetworkConnectedState);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::OpenTCPSocketSta~::ESP32C_OK::[else]}
            else {
                //QEvt evt(ESP32C_ERR_SIG);
                //this->DISPATCH(&evt,getPrio());

                #if !Q_UTEST

                   QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
                   this->POST(evt,this);

                #endif
                status_ = Q_RET_HANDLED;
            }
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitDataState}
Q_STATE_DEF(AO_ESP32C, TransmitDataState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitDataState}
        case Q_ENTRY_SIG: {
            // reset api result buffer
            commandParseResult = false;
            // start timeout timer
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_WIFI_CONN_INTERVAL_MS,
                            0);
            init.esp->SendData(send_data_buffer);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitDataState}
        case Q_EXIT_SIG: {
            m_timeEvt.disarm();

            error_counter = 0;
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitDataStat~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            #if !Q_UTEST
                AO_ESP32C_SendDataCallback(this, false, client_link_id);
                TRACE_AO_ESP32C("TxErr");
                memset(rx_buffer, 0, sizeof(rx_buffer));
                // Flush received data
                init.esp->FlushRx();
            #endif
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitDataStat~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            //commandParseResult = init.esp->Parse_SendData();
            commandParseResult = true;
            #if Q_UTEST
                commandParseResult = true;
            #endif
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitDataStat~::ESP32C_OK::[response_ok]}
            if (commandParseResult == true) {
                timeout_counter = 0;
                error_counter = 0;
                #if !Q_UTEST
                    if(socket_status[client_link_id] == ESP32C_SOCKET_STATUS_OPEN )
                    {
                        AO_ESP32C_SendDataCallback(this, true, client_link_id);
                    }
                    else if(socket_status[client_link_id] == ESP32C_SOCKET_STATUS_WS_OPEN )
                    {
                        AO_ESP32C_WebSocketSendCallback(this, true, client_link_id);
                    }
                    TRACE_AO_ESP32C("TxCmplt");
                #endif
                status_ = tran(&Idle_NetworkConnectedState);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitDataStat~::ESP32C_OK::[else]}
            else {
                #if !Q_UTEST
                   TRACE_AO_ESP32C("SendError");
                   QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
                   this->POST(evt,this);

                #endif
                status_ = Q_RET_HANDLED;
            }
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::InitiateSendDataState}
Q_STATE_DEF(AO_ESP32C, InitiateSendDataState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::InitiateSendDataState}
        case Q_EXIT_SIG: {
            m_timeEvt.disarm();
            error_counter = 0;
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::InitiateSendData~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            #if !Q_UTEST


            AO_ESP32C_SendDataCallback(this, false, client_link_id);

            #endif
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::InitiateSendData~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            commandParseResult = init.esp->Parse_AT_CIPSEND();
            #if Q_UTEST
                commandParseResult = true;
            #endif
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::InitiateSendData~::ESP32C_OK::[ready_to_send]}
            if (true == commandParseResult) {
                error_counter = 0;
                status_ = tran(&TransmitDataState);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::InitiateSendData~::ESP32C_OK::[else]}
            else {

                #if !Q_UTEST

                   QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
                   this->POST(evt,this);

                #endif
                status_ = Q_RET_HANDLED;
            }
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WaitingForDataState}
Q_STATE_DEF(AO_ESP32C, WaitingForDataState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WaitingForDataState}
        case Q_ENTRY_SIG: {
            m_timeEvt.disarm();
            m_timeEvt.armX( user_timeout_ms,
                            0);
            // wait for data
            //init.esp->WaitData();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WaitingForDataState}
        case Q_EXIT_SIG: {
            m_timeEvt.disarm();

            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WaitingForDataSt~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            AO_ESP32C_ReadCompleteCallback(this, false);
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WaitingForDataSt~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            timeout_counter = 0;
            if(rx_data_length<= receive_data_max_length)
            {
                TRACE_AO_ESP32C("RCV_OK,%d",rx_data_length);
                memcpy(receive_data_buffer_ptr,
                        rx_buffer,
                        rx_data_length);
                AO_ESP32C_ReadCompleteCallback(this, true);
            }
            else
            {
                TRACE_AO_ESP32C("RCV_Ko,Overflow%d",rx_data_length);
                AO_ESP32C_ReadCompleteCallback(this, false);
            }


            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenState}
Q_STATE_DEF(AO_ESP32C, WebSocket_OpenState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenState}
        case Q_EXIT_SIG: {
            error_counter = 0;
            m_timeEvt.disarm();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            TRACE_AO_ESP32C("WspE,Link%d", (uint8_t)client_link_id);
            // next retry, use a different link id
            client_link_id =
                                static_cast<DRV::ESP32C3::LinkId>((
                                (uint8_t)client_link_id+1)%
                                ESP32C3_MAX_WS_SOCKET);
            // increase error counter
            error_counter++;
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::ESP32C_ERR::[retriesavailable]}
            if (error_counter<ESP32C_RETRY_MAX) {
                status_ = tran(&Send_AT_WSCFG);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::ESP32C_ERR::[else]}
            else {
                TRACE_AO_ESP32C("Wsp End of Retries");
                socket_status[client_link_id] = ESP32C_SOCKET_STATUS_CLOSE;
                AO_ESP32C_WebSocketOpenCallback(this, false, client_link_id);
                client_link_id = DRV::ESP32C3::LinkId0;
                status_ = tran(&Idle_NetworkConnectedState);
            }
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSCFG}
Q_STATE_DEF(AO_ESP32C, Send_AT_WSCFG) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSCFG}
        case Q_ENTRY_SIG: {
            commandParseResult = false;
            bool socketFound = GetFreeWsSocketId(&client_link_id);


            /* see if there is a free link id (socket id)*/
            if(socketFound)
            {
                if(ws_cfg_done[client_link_id] == true)
                {
                    #if !Q_UTEST

                        QEvt *evt = Q_NEW(QEvt, ESP32C_OK_SIG);
                        this->POST(evt,this);
                        TRACE_AO_ESP32C("Skip Config");
                    #endif
                }
                else
                {
                    /* issue the at+cip start command */
                    init.esp->Send_AT_WSCFG(
                                  client_link_id,
                                  ws_ping_interval_s,
                                  ws_ping_timeout_s );
                    m_timeEvt.disarm();
                    m_timeEvt.armX( ESP32C_WS_INTERVAL_MS,
                                    0);
                }
            }else{
               /* dispatch err sig*/
            #if !Q_UTEST

               QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
               this->POST(evt,this);

            #endif
            }

            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSCFG::ESP32C_OK}
        case ESP32C_OK_SIG: {
            commandParseResult = true;
            ws_cfg_done[client_link_id] = true;
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSCFG::ESP32C_OK::[no_header_required]}
            if (ws_header_len == 0) {
                status_ = tran(&Send_AT_WSOPEN);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSCFG::ESP32C_OK::[header_required]}
            else {
                status_ = tran(&Send_AT_WSHEAD);
            }
            break;
        }
        default: {
            status_ = super(&WebSocket_OpenState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSHEAD}
Q_STATE_DEF(AO_ESP32C, Send_AT_WSHEAD) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSHEAD}
        case Q_ENTRY_SIG: {
            commandParseResult = false;
            TRACE_AO_ESP32C("Conf WS Header");
            /* issue the at+cip start command */
            init.esp->Send_AT_WSHEAD(
                          ws_header_len);
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_WS_INTERVAL_MS,
                            0);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSHEAD::ESP32C_OK}
        case ESP32C_OK_SIG: {
            // parse the response, the response is the same as of AT+CIPSEND
            commandParseResult = init.esp->Parse_AT_CIPSEND();
            #if Q_UTEST
                commandParseResult = true;
            #endif
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSHEAD::ESP32C_OK::[readytosendheader]}
            if (true == commandParseResult) {
                TRACE_AO_ESP32C("Rdy to Send Header");
                status_ = tran(&Send_Header);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSHEAD::ESP32C_OK::[else]}
            else {
                #if !Q_UTEST
                   TRACE_AO_ESP32C("Bad Header Trans");
                   QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
                   this->POST(evt,this);

                #endif
                status_ = Q_RET_HANDLED;
            }
            break;
        }
        default: {
            status_ = super(&WebSocket_OpenState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSOPEN}
Q_STATE_DEF(AO_ESP32C, Send_AT_WSOPEN) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSOPEN}
        case Q_ENTRY_SIG: {
            commandParseResult = false;
            TRACE_AO_ESP32C("Prepare Open Ws");
            /* issue the at+cip start command */
            if(ws_sub_protocol_len > 0)
            {
                if(ws_auth_len>0)
                {
                    init.esp->Send_AT_WSOPEN(client_link_id,
                                 ws_uri, ws_sub_protocol, ws_auth );
                }
                else
                {
                    init.esp->Send_AT_WSOPEN(client_link_id,
                                         ws_uri, ws_sub_protocol, nullptr );
                }
            }else
            {
                init.esp->Send_AT_WSOPEN(client_link_id,
                                     ws_uri, nullptr, nullptr );
            }

            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_WS_INTERVAL_MS,
                                0);

            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSOPEN::ESP32C_OK}
        case ESP32C_OK_SIG: {
            DRV::ESP32C3::LinkId link;
            commandParseResult = init.esp->Parse_AT_WSOPEN( &link);
            TRACE_AO_ESP32C("WsOpenOk");
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSOPEN::ESP32C_OK::[responseok]}
            if (commandParseResult == true) {
                socket_status[client_link_id] = ESP32C_SOCKET_STATUS_WS_OPEN;
                timeout_counter = 0;
                AO_ESP32C_WebSocketOpenCallback(this, true, client_link_id);
                status_ = tran(&Idle_NetworkConnectedState);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_AT_WSOPEN::ESP32C_OK::[else]}
            else {
                #if !Q_UTEST

                   QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
                   this->POST(evt,this);
                    TRACE_AO_ESP32C("Ws Open Err");
                #endif
                status_ = Q_RET_HANDLED;
            }
            break;
        }
        default: {
            status_ = super(&WebSocket_OpenState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_Header}
Q_STATE_DEF(AO_ESP32C, Send_Header) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_Header}
        case Q_ENTRY_SIG: {

            // reset api result buffer
            commandParseResult = false;
            // start timeout timer
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_WIFI_CONN_INTERVAL_MS,
                            0);
            TRACE_AO_ESP32C("Deliver Header");
            init.esp->Send_WsHeader(ws_header);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_OpenSt~::Send_Header::ESP32C_OK}
        case ESP32C_OK_SIG: {
            timeout_counter = 0;
            TRACE_AO_ESP32C("Header Deliver Ok");
            status_ = tran(&Send_AT_WSOPEN);
            break;
        }
        default: {
            status_ = super(&WebSocket_OpenState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::Websocket_SendState}
Q_STATE_DEF(AO_ESP32C, Websocket_SendState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::Websocket_SendState}
        case Q_EXIT_SIG: {
            error_counter = 0;
            m_timeEvt.disarm();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::Websocket_SendSt~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            #if !Q_UTEST

                AO_ESP32C_WebSocketSendCallback(this, false, client_link_id);
                memset(rx_buffer, 0, sizeof(rx_buffer));
                // Flush received data
                init.esp->FlushRx();
            #endif
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::Websocket_SendSt~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            commandParseResult = init.esp->Parse_AT_CIPSEND();
            #if Q_UTEST
                commandParseResult = true;
            #endif
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::Websocket_SendSt~::ESP32C_OK::[responseok]}
            if (commandParseResult == true) {
                timeout_counter = 0;
                TRACE_AO_ESP32C("SendCmdOk");
                status_ = tran(&TransmitWebSocketDataState);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::Websocket_SendSt~::ESP32C_OK::[else]}
            else {

                #if !Q_UTEST

                   QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
                   this->POST(evt,this);
                    TRACE_AO_ESP32C("SndErr");
                #endif
                status_ = Q_RET_HANDLED;
            }
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_CloseState}
Q_STATE_DEF(AO_ESP32C, WebSocket_CloseState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_CloseState}
        case Q_EXIT_SIG: {
            m_timeEvt.disarm();
            socket_status[client_close_id] = ESP32C_SOCKET_STATUS_CLOSE;
            AO_ESP32C_WebSocketCloseCallback(this, true,  client_close_id);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_CloseS~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            timeout_counter = 0;
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::WebSocket_CloseS~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitWebSocketDataState}
Q_STATE_DEF(AO_ESP32C, TransmitWebSocketDataState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitWebSocketDataState}
        case Q_ENTRY_SIG: {
            // reset api result buffer
            commandParseResult = false;
            // start timeout timer
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_WIFI_CONN_INTERVAL_MS,
                            0);
            init.esp->SendWebSocketData(send_data_buffer);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitWebSocketDataState}
        case Q_EXIT_SIG: {
            m_timeEvt.disarm();

            error_counter = 0;
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitWebSocke~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            #if !Q_UTEST

                AO_ESP32C_WebSocketSendCallback(this, false, client_link_id);

                TRACE_AO_ESP32C("WsTxErr");
            #endif
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::TransmitWebSocke~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            AO_ESP32C_WebSocketSendCallback(this,
                                             true,
                                             client_link_id);

            timeout_counter = 0;
            TRACE_AO_ESP32C("Deliver PayLoadOk");
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CreateServerState}
Q_STATE_DEF(AO_ESP32C, CreateServerState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CreateServerState}
        case Q_ENTRY_SIG: {
            // reset command result buffer
            commandParseResult = false;
            //send command to module
            init.esp->Send_AT_CIPSERVERMAXCONN(server_max_connections);
            // prepare timeout timer
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_TIMEOUT_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CreateServerState}
        case Q_EXIT_SIG: {
            m_timeEvt.disarm();

            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CreateServerStat~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            AO_ESP32C_ServerOpenCallback(this, false);
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CreateServerStat~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            m_timeEvt.disarm();
            status_ = tran(&open_server);
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CreateServerStat~::open_server}
Q_STATE_DEF(AO_ESP32C, open_server) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CreateServerStat~::open_server}
        case Q_ENTRY_SIG: {
            // reset command result buffer
            commandParseResult = false;
            //send command to module
            init.esp->Send_AT_CIPSERVER(DRV::ESP32C3::Create_Server, server_port);
            // prepare timeout timer
            m_timeEvt.disarm();
            m_timeEvt.armX( ESP32C_TIMEOUT_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CreateServerStat~::open_server::ESP32C_OK}
        case ESP32C_OK_SIG: {
            m_timeEvt.disarm();
            #if !Q_UTEST
                commandParseResult = init.esp->Parse_AT_CIPSERVER();
            #else
                commandParseResult = true;
            #endif
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CreateServerStat~::open_server::ESP32C_OK::[commandsuccessful]}
            if (commandParseResult == true) {
                AO_ESP32C_ServerOpenCallback(this, true);
                error_counter = 0;
                timeout_counter = 0;
                status_ = tran(&Idle_NetworkConnectedState);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::CreateServerStat~::open_server::ESP32C_OK::[else]}
            else {

                #if !Q_UTEST

                   QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
                   this->POST(evt,this);

                #endif
                status_ = Q_RET_HANDLED;
            }
            break;
        }
        default: {
            status_ = super(&CreateServerState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::UdpListenCommandState}
Q_STATE_DEF(AO_ESP32C, UdpListenCommandState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::UdpListenCommandState}
        case Q_ENTRY_SIG: {
            client_link_id = DRV::ESP32C3::LinkId0;
            if(GetFreeSocketId(&client_link_id))
            {
                /* issue the at+cip start command */
                init.esp->Send_AT_CIPSTART(client_link_id,
                                     DRV::ESP32C3::UDP,
                                     remote_address,
                                     udp_remote_port,
                                     udp_local_port);
                m_timeEvt.disarm();
                m_timeEvt.armX( ESP32C_TCP_INTERVAL_MS,
                                0);
            }else{
               /* dispatch err sig*/
            #if !Q_UTEST

               QEvt *evt = Q_NEW(QEvt, ESP32C_ERR_SIG);
               this->POST(evt,this);

            #endif
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::UdpListenCommand~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::UdpListenCommand~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            m_timeEvt.disarm();
            socket_status[client_link_id] = ESP32C_SOCKET_STATUS_OPEN;
            timeout_counter = 0;
            AO_ESP32C_UdpSocketOpenCallback(this, true, client_link_id );
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::ConnectionCheckState}
Q_STATE_DEF(AO_ESP32C, ConnectionCheckState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::ConnectionCheckState}
        case Q_EXIT_SIG: {
            m_connectionCheckTimeEvt.disarm();
            m_timeEvt.disarm();
            m_connectionCheckTimeEvt.armX( ESP32C_AO_CONNECTION_CHECK_PERIOD_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::ConnectionCheckS~::ESP32C_OK}
        case ESP32C_OK_SIG: {
            #if !Q_UTEST
                DRV::ESP32C3::ConnectionState_t conn;
                commandParseResult = init.esp->Parse_AT_CWSTATE(&conn);
                if(true == commandParseResult && conn != DRV::ESP32C3::Connected_IpObtained)
                {
                   TRACE_AO_ESP32C("ChkWifiAPDisconn");

                   AO_ESP32C_WifiDisconnectionCallback(this, true);
                   commandParseResult = false;
                }else if(!commandParseResult)
                {
                    TRACE_AO_ESP32C("WrngChk");
                }
            #else
                commandParseResult = true;
            #endif
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::ConnectionCheckS~::ESP32C_OK::[connectionOK]}
            if (true == commandParseResult) {
                status_ = tran(&Idle_NetworkConnectedState);
            }
            //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::ConnectionCheckS~::ESP32C_OK::[else]}
            else {
                status_ = Q_RET_HANDLED;
            }
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Idle_ConfiguredS~::Busy_NetworkConn~::ConnectionCheckS~::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            status_ = tran(&Idle_NetworkConnectedState);
            break;
        }
        default: {
            status_ = super(&Busy_NetworkConnectedState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Base_ConfigState} .........................
Q_STATE_DEF(AO_ESP32C, Base_ConfigState) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState}
        case Q_ENTRY_SIG: {
            for(uint8_t i = 0; i<(uint8_t)DRV::ESP32C3::LinkIdMax; i++)
            {
                socket_status[i] = ESP32C_SOCKET_STATUS_CLOSE;
            }
            for(uint8_t i = 0; i<ESP32C3_MAX_WS_SOCKET; i++)
            {
                ws_cfg_done[i] = false;
            }
            hotspot_active = false;
            init.esp->SetUrcReadiness(false);
            // empty the defer queue
            bool recalled = this->recall(init.deferQueue);
            while(recalled)
            {
              recalled = this->recall(init.deferQueue);
            }
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::initial}
        case Q_INIT_SIG: {
            status_ = tran(&ResetStart);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            m_timeEvt.disarm();
            status_ = tran(&ResetStart);
            break;
        }
        default: {
            status_ = super(&InitState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendAT} .................
Q_STATE_DEF(AO_ESP32C, SendAT) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendAT}
        case Q_ENTRY_SIG: {
            init.esp->Send_AT();
            m_timeEvt.armX( ESP32C_TIMEOUT_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendAT::ESP32C_OK}
        case ESP32C_OK_SIG: {
            m_timeEvt.disarm();
            status_ = tran(&SendAT_SYSTORE);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendAT::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&Base_ConfigState);
            break;
        }
        default: {
            status_ = super(&Base_ConfigState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SetMode} ................
Q_STATE_DEF(AO_ESP32C, SetMode) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SetMode}
        case Q_ENTRY_SIG: {
            init.esp->Send_AT_CWMODE(mode);
            m_timeEvt.armX( ESP32C_TIMEOUT_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SetMode}
        case Q_EXIT_SIG: {
            TRACE_AO_ESP32C("MODECONFEXT");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SetMode::ESP32C_OK}
        case ESP32C_OK_SIG: {
            m_timeEvt.disarm();
            init.esp->SetUrcReadiness(true);
            TRACE_AO_ESP32C("MODECONFTRAN");
            AO_ESP32C_ConfigCompleteCallback(this);
            timeout_counter = 0;
            status_ = tran(&Idle_ConfiguredState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SetMode::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&Base_ConfigState);
            break;
        }
        default: {
            status_ = super(&Base_ConfigState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::ResetEnd} ...............
Q_STATE_DEF(AO_ESP32C, ResetEnd) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::ResetEnd}
        case Q_ENTRY_SIG: {
            init.esp->StopReset();
            // and periodically every 1 second
            m_timeEvt.armX( ESP32C_RESET_INTERVAL_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::ResetEnd::TIMEOUT}
        case TIMEOUT_SIG: {
            m_timeEvt.disarm();
            status_ = tran(&SendAT);
            break;
        }
        default: {
            status_ = super(&Base_ConfigState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendCIPMUX} .............
Q_STATE_DEF(AO_ESP32C, SendCIPMUX) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendCIPMUX}
        case Q_ENTRY_SIG: {
            init.esp->Send_AT_CIPMUX(true);
            m_timeEvt.armX( ESP32C_TIMEOUT_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendCIPMUX::ESP32C_OK}
        case ESP32C_OK_SIG: {
            m_timeEvt.disarm();
            status_ = tran(&SetMode);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendCIPMUX::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&Base_ConfigState);
            break;
        }
        default: {
            status_ = super(&Base_ConfigState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::Disconnect} .............
Q_STATE_DEF(AO_ESP32C, Disconnect) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::Disconnect}
        case Q_ENTRY_SIG: {
            init.esp->Send_AT_CWQAP();
            m_timeEvt.armX( ESP32C_TIMEOUT_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::Disconnect::ESP32C_OK}
        case ESP32C_OK_SIG: {
            m_timeEvt.disarm();
            status_ = tran(&SendCIPMUX);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::Disconnect::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&Base_ConfigState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::Disconnect::ESP32C_ERR}
        case ESP32C_ERR_SIG: {
            m_timeEvt.disarm();
            status_ = tran(&SendCIPMUX);
            break;
        }
        default: {
            status_ = super(&Base_ConfigState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendAT_SYSTORE} .........
Q_STATE_DEF(AO_ESP32C, SendAT_SYSTORE) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendAT_SYSTORE}
        case Q_ENTRY_SIG: {
            init.esp->Send_AT_SYSSTORE(false);
            m_timeEvt.armX( ESP32C_TIMEOUT_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendAT_SYSTORE::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&Base_ConfigState);
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::SendAT_SYSTORE::ESP32C_OK}
        case ESP32C_OK_SIG: {
            m_timeEvt.disarm();
            status_ = tran(&Disconnect);
            break;
        }
        default: {
            status_ = super(&Base_ConfigState);
            break;
        }
    }
    return status_;
}

//${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::ResetStart} .............
Q_STATE_DEF(AO_ESP32C, ResetStart) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::ResetStart}
        case Q_ENTRY_SIG: {
            init.esp->StartReset();
            m_timeEvt.disarm();
            // and periodically every 1 second
            m_timeEvt.armX( ESP32C_RESET_INTERVAL_MS,
                            0);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::AO_ESP32C::SM::InitState::Base_ConfigState::ResetStart::TIMEOUT}
        case TIMEOUT_SIG: {
            m_timeEvt.disarm();
            status_ = tran(&ResetEnd);
            break;
        }
        default: {
            status_ = super(&Base_ConfigState);
            break;
        }
    }
    return status_;
}

} // namespace AO
//$enddef${AOs::AO_ESP32C} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


